name: Nightly Codespace Deployment

on:
  push:
    branches:
      - main
  schedule:
    # Runs every day at 4:00 AM pacific (UTC-7)
    - cron: '0 12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Codespace
        env:
          GITHUB_TOKEN: ${{ secrets.CODESPACES_TOKEN }}
        run: |
          # Define variables
          OWNER="danwahlin"
          REPO="angular-test"
          BRANCH="main" # or your specific branch
          API_URL="https://api.github.com/repos/$OWNER/$REPO/codespaces"
          APP_PORT=4200

          # Make API call to create a Codespace
          response=$(curl -X POST $API_URL \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"ref\": \"$BRANCH\"}")

          codespace_api_url=$(echo $response | jq -r '.url')
          codespace_url=$(echo $response | jq -r '.web_url')
          echo "Codespace URL: $codespace_url"

          # Replace web_url value to get to desired port
          # BEFORE: https://fantastic-space-carnival-54p976wp3v95v.github.dev
          # AFTER: https://fantastic-space-carnival-54p976wp3v95v-4200.app.github.dev
          app_url=$(echo $codespace_url | sed "s|.github.dev|-${APP_PORT}.app.github.dev|g")

          # Wait for Codespace to be ready
          echo "Waiting 60 seconds for Codespace to be ready between attempts..."
          # Simple polling mechanism
          for i in {1..20}; do 
            ngResponse=$(curl -s -o /dev/null -w "%{http_code}" $app_url)
            if [ "$ngResponse" == "200" ]; then
              echo "App is ready"
              break
            else
              echo "Waiting for the app to be ready... attempt $i (HTTP response: $ngResponse)"
              sleep 60 # Wait for 60 seconds before trying again
            fi
          done       

          # Delete Codespace
          deleteResponse=$(curl -X -s DELETE $codespace_api_url \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json")
        
          echo "Deleted codespace"
        

