name: Nightly Codespace Deployment

on:
  push:
    branches:
      - main
#   schedule:
#     # Runs every day at 2:00 AM UTC
#     - cron: '0 2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Codespace
        env:
          GITHUB_TOKEN: ${{ secrets.CODESPACES_TOKEN }}
        run: |
          # Define variables
          OWNER="danwahlin"
          REPO="angular-test"
          BRANCH="main" # or your specific branch
          API_URL="https://api.github.com/repos/$OWNER/$REPO/codespaces"

          # Make API call to create a Codespace
          response=$(curl -X POST $API_URL \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"ref\": \"$BRANCH\"}")

          echo "Response: $response"

